name: scam_shield
description: A full-featured Scam Shield Flutter app.

publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  flutter_animate: ^4.0.0
  url_launcher: ^6.1.10

flutter:
  uses-material-design: true
